version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: samal
      MYSQL_DATABASE: times
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    container_name: times-zone-container
    image: samal024/timeszone
    restart: always
    environment:
      PROFILE: dev
      EMAIL_ADDRESS: samal.anjukandiyil@gmail.com
      EMAIL_PASSWORD: qyxc bauc
      DATABASE_HOST: db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: samal
      RAZORPAY_ID: rpy_test
      RAZORPAY_SECRET: rpy_secret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mysql: